### PR TITLE
remove inheritance of PkModel at QuizStudentLinkInDBBase

### PR DESCRIPTION
**Pull request by Iionsroar**
- fix for https://github.com/Iionsroar/inquizitor/issues/22
- see `Files changed` tab for more info

### CODE REVIEW

**Comment by Iionsroar** [comment]
see `files changed` tab and check the model definitions for `QuizStudentLink`

**Comment by ralf-t** [comment]
Bale magiging composite primary key sila no para di maulit?

**Comment by Iionsroar** [comment]
yep ganun ata siya gumagana

**Comment by ralf-t** [comment]
Ohhhh oki looks good to me

**Pull request merged**
