### PR TITLE
add question type

### PR DESCRIPTION
**Pull request by Iionsroar**
### for review:
- **backend:** code quality & methodology (see files changed tab)
- **frontend:** feasibility/ usability

### CODE REVIEW

**Comment by ralf-t** [comment]
Ano mas better design?

**A:**
- Mag lagay tayo ng additional field like "answer" sa quizquestion na fillable lang pag quiz type ay fill in the blanks
- This means pala na isa lang ang acceptable answer

**B:**
- Gawa ng choices for correct answers (na hindi dapat i display sa frontend, compared sa multiple choice)
- Tapos para magka quizanswer, iququery kung yung sagot ng user ay nasa choices? (that means magiging nullable yung choice_id pag walang match na correct answer)

**Comment by Iionsroar** [comment]
- Nullable ba yung `QuizAnswer` for both **A** and **B**?
- For **A**, idk ano pwedeng gawin para maaccept multiple answers

**Comment by ralf-t** [comment]
For A, magiging null lang pag hindi sinagutan (pero saka na implement pag hinanap?)
For B, magiging null yung answer kapag walang match sa choices. Which means, it's wrong.

Right now tingin ko mas maganda yung B kasi logic lang babaguhin hindi yung overall schema.

**Comment by Iionsroar** [comment]
I think naimplement na yung nullable sa latest commit, will check n test later

**Comment by ralf-t** [comment]
g g g g

**Comment by xtian18** [comment]
- pano na pala sistema sa pag-uupdate ng answer pag fill in the blank? ganito kasi sinesend kong formdata dati e
image

- tsaka nung nagaaccess pala ako ng quiz sa student account, may lumalabas na ganto although walang ganto dati and wala akong binago sa code
image

**Comment by Iionsroar** [comment]
@xtian18 

1. For fill-in-the-blanks, di na need yung `choice_id` at `is_correct` (ang alam ko di na rin need yung `is_correct` sa multiple-choice type, patest na lang din) 
2. Backend issue pala to sa main, nafix na siya and namerge na sa branch na to, patry ulit thanks

**Review by ralf-t — APPROVED** [review]
If wala na bugs for frontend im g

**Comment by Iionsroar** [comment]
wait ko na lang updates nila @xtian18 at @XSeed21 if no problems na with the latest commits

**Comment by xtian18** [comment]
ok na pala sa front end

**Pull request merged**
